/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model (props) {

  const group = useRef()

  // const mesh = useRef()
  const { nodes, materials } = useGLTF('/NIVA.gltf')

  // const [active, setActive] = useState(false)

  // const [colour, setColour] = useState('#ED91AD')

  return (
    <group ref = {group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Oil Slick']} >
        {/* <mesh onClick={()=>{ colour === '#ED91AD' ? setColour('#93c572') : setColour('#ED91AD')}} geometry={nodes.Icing.geometry} material={nodes.Icing.material} material-color={colour}/> */}
      </mesh>
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} position={[-4.43, 0, 0]} rotation={[0, 0, -1.57]} scale={8.43} />
    </group>
  )
}

useGLTF.preload('/NIVA.gltf')
