listChar = """https://github.com/patalwell
https://github.com/trentlilley
https://github.com/pymoura
https://github.com/Tiger101010
https://github.com/Christina0114
https://github.com/jgrant12345
https://github.com/josepylee
https://github.com/Krito1997
https://github.com/lonnie-nguyen
https://github.com/tahaziauci
https://github.com/heartlessnan
https://github.com/apriyanka3107
https://github.com/matiarasianipar
https://github.com/nahal99
https://github.com/michaelnguyen26
https://github.com/Cheryl0402
https://github.com/tunghsul
https://github.com/shihlei
https://github.com/Carlwasinfected
https://github.com/xrk-git
https://github.com/yx-hh
https://github.com/JingGu101
https://github.com/kanebetter
https://github.com/victoriacooperworld
https://github.com/nontoother
https://github.com/SSSSam141
https://github.com/kanebetter
https://github.com/Jason-TianrenTan
https://github.com/rustberry
https://github.com/13542
https://github.com/tiffanychao
https://github.com/Lazurite259
https://github.com/CarolynLo
https://github.com/tomlinn
https://github.com/zichengshan
https://github.com/z1514
https://github.com/chenxu-wang
https://github.com/JoshuaSunsheng
https://github.com/jjlock
https://github.com/Jimmykoki
https://github.com/toadius2
https://github.com/yrfang
https://github.com/yuchesu
https://github.com/JiayiLi1999
https://github.com/yinpeng0528
https://github.com/BinGuo0717
https://github.com/ruiyan-ma
https://github.com/jt-chae
https://github.com/StellaMaUCI
https://github.com/sunsetcoder
"""

for site in listChar.split("\n"):
    print(site.split('/')[-1],end=',')
